version: '3'
services:
  gateway:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: gateway
    command: sh -c "
       python3 manage.py makemigrations &&
       python3 manage.py migrate --noinput &&
       python3 manage.py collectstatic --noinput &&
       python3 manage.py shell -c 
        'from django.contrib.auth.models import User; 
         User.objects.filter(username=\"$DJANGO_SUPERUSER_USERNAME\").exists() or 
        User.objects.create_superuser(\"$DJANGO_SUPERUSER_USERNAME\", \"$DJANGO_SUPERUSER_EMAIL\", \"$DJANGO_SUPERUSER_PASSWORD\")
        ' &&
       python3 manage.py runserver 0.0.0.0:8089"
    restart: always
    volumes:
      - .:/app
    expose:
      - "8089"
    env_file:
      - .env
    depends_on:
      - db
  
  db:
    image: postgres
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgre$

  kong:
    image: kong_nodb
    container_name: kong_nodb
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_ADMIN_GUI_URL: http://127.0.0.1:8002
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_LOG_LEVEL: debug 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8000"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8000:8000/tcp"
      - "8001:8001/tcp"
      - "8002:8002/tcp"
      - "8444:8444/tcp"

  keycloak_postgres:
    container_name: keycloak_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_KC_USER}
      POSTGRES_PASSWORD: ${POSTGRES_KC_PASSWORD}
      POSTGRES_PORT: 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    ports:
      - "8080:8080"
    environment:
        KEYCLOAK_ADMIN: ${KEYCLOAK_USER}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
        KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
        KC_DB: postgres
        KC_DB_USERNAME: ${POSTGRES_KC_USER}
        KC_DB_PASSWORD: ${POSTGRES_KC_PASSWORD}
    depends_on:
      - keycloak_postgres
    command: 
      - start-dev

volumes:
  postgres_data: